# Generated by Django 3.1.7 on 2021-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_jobentreprise_jobperso'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobperso',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
