# Generated by Django 3.1.7 on 2021-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0003_auto_20211007_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentreprise',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
