# Generated by Django 3.1.7 on 2021-10-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_jobentreprise_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobentreprise',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobperso',
            old_name='decription',
            new_name='description',
        ),
    ]
