# Generated by Django 3.1.7 on 2021-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0005_auto_20211007_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobentreprise',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobperso',
            name='date_to',
            field=models.DateField(),
        ),
    ]
