# Generated by Django 3.1.7 on 2021-10-12 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portefolio', '0006_auto_20211007_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('eyes', models.IntegerField(default=0)),
                ('categorie', models.ManyToManyField(blank=True, null=True, to='portefolio.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
