# Generated by Django 3.1.7 on 2021-10-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0007_category_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentreprise',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, to='portefolio.Category'),
        ),
        migrations.AddField(
            model_name='jobperso',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, to='portefolio.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, to='portefolio.Category'),
        ),
    ]
