# Generated by Django 3.1.7 on 2021-10-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0008_auto_20211012_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categorie',
        ),
    ]
