# Generated by Django 3.1.7 on 2021-10-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0010_jobentreprise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobentreprise',
            name='user',
        ),
    ]
