# Generated by Django 3.1.7 on 2021-10-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portefolio', '0015_auto_20211013_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobperso',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobpersos', to='auth.user'),
            preserve_default=False,
        ),
    ]
