# Generated by Django 3.1.7 on 2021-10-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0017_auto_20211023_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
