# Generated by Django 3.1.7 on 2021-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesplace',
            name='website_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='archivesplace',
            name='website_link_second',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
