# Generated by Django 3.1.7 on 2022-01-14 01:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20211210_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesplace',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='archivesplace',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
