# Generated by Django 3.1.7 on 2022-01-12 22:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0004_texte_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
