# Generated by Django 4.0.3 on 2022-03-10 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0005_auto_20220112_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique_for_date='date_created')),
                ('body', models.TextField()),
                ('photho1', models.ImageField(upload_to='image_files')),
                ('photho2', models.ImageField(blank=True, null=True, upload_to='image_files')),
                ('publish_by', models.CharField(max_length=200)),
                ('like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleposts', to='creativite.categoriespost')),
            ],
        ),
    ]
