# Generated by Django 4.0.3 on 2022-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0006_categoriespost_articlepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
