# Generated by Django 4.0.3 on 2022-04-05 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0007_alter_articlepost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replypost', to='creativite.articlepost')),
            ],
        ),
    ]
