# Generated by Django 4.0.3 on 2022-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0008_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
    ]
