# Generated by Django 4.0.3 on 2022-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativite', '0010_useriptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
